name: Flutter CI

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mobile  # 👈 Set working directory to your Flutter app

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.1'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze Dart code
        run: flutter analyze

      - name: Run tests
        run: flutter test

      # Optional: Build APK
      - name: Build APK
        run: flutter build apk --debug